name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
assignees: [SampleAssignee]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the feature request...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why is this feature important to you?
      placeholder: Explain why this feature would be useful...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How would you like this feature to be implemented?
      placeholder: Describe the implementation idea...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: List any alternative approaches...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other relevant information?
      placeholder: Add any extra context here...